### ISSUE TITLE
Skype

### ISSUE THREAD

**Issue by delemojo** [PolskaBot/PolskaBotCore#1]
Hey dude could u add me on Skype? I want to talk to u, cause I would like to know how to transfer data from one stream to another while using your Core Parser to handle the Packets.

skype: dennisjv3

**Comment by Sekhmet** [comment]
Sorry, I don't use Skype.

Parser is more or less abstract, so you shouldn't have problems plugging it in to whatever you want.

I am afraid I don't get your question. If you want to proxy all requests from some socket to another, just decrypt packets while receiving from socket A and send it to socket B, same applies to sending from B to A, except you need to encrypt packets.

I would get rid of most code from our source, just use ExternalInterface to communicate with SWF. Just keep in mind it's outdated and you will have to uptade some keys in SWF (and possibly entire SWF if BP updated their encryption).

**Comment by delemojo** [comment]
Well I will just try to explain it ^^. So I have my BOT(which is using a WebBrowser so I just send packets under it). Than I have a SOCKS5 Proxy and a Third Party Program called Proxifier.
Lets say the SOCKS5 Proxy is running on IP 1.1.1.1:1090 than Proxifier will redirect all incoming traffic from the BOTs WebBrowser, if the packets that are being send come from/go to Port 8080, to 1.1.1.1:1090.
The SOCKS5 Server than directs it to the BOTs WebBrowser and sends the data to the connected TCP Client(Your Core File). But here comes the Problem, how to write the packets that the SOCKS5 Server recieved on the TCPClients stream? I mean I know how but it wont work right. The SOCKS5 Server only gives as EventArgs the Buffer, Offset, Count, Reqeust(IP, Port etc.) and the Client(from where the data was recieved).
I tried writing it on the TCPClient stream with the EndianWriter like:
writer.Write((short)(Buffer.Length + 2));
writer.Write(Buffer);

But than the Packet ID is missing.
I also tried clientstream.write(Buffer, Offster, Buffer.Length);

But this sadly did not work either.
Do u have any idea?

**Comment by Sekhmet** [comment]
I think that SOCKS5 servers send you packets in BigEndian  already, so you should just send it straight away. It's hard to say, as you have multiple points where transformation from BE to LE might happen. You should debug your code and see what's going on with your packets.

**Comment by delemojo** [comment]
`byte[] array = new byte[e.Count];
                Array.Copy(e.Buffer, array, e.Count);
                e.Buffer = (new byte[array.Length]);
                e.Buffer = (array);
                Client.Send(e.Buffer, e.Offset, e.Buffer.Length);`

This is what I do with the incoming packets (SOCKS5).
And than I send them to the Bot like this:
`clientStream.Write(Buffer, Offset, Count);
            clientStream.Flush();`

**Comment by Sekhmet** [comment]
You might create repo with your code so I can take closer look on it.

As it's unrelated to this repo I'm closing this issue.
