### ISSUE TITLE
ClientReuqestCode ID

### ISSUE THREAD

**Issue by delemojo** [PolskaBot/PolskaBotCore#2]
Hi its me again =D
I have a problem with finding the ClientRequestCode ID in the main.swf, I updated everything else like Fade.swf Pandora BigIntegers etc. But I cant find the ClientRequestCode ID in the main.swf. Do u have any idea where to find it? =)

**Comment by Sekhmet** [comment]
Look in the main.swf how encryption handshake is made.

**Comment by delemojo** [comment]
Yes found everything thx. But now I dont recive the "ServerRequestCallback" or anything after I got StageOne. I thought about that, that I need to answer to the Server the "StageOne Code" but I couldnt find anything in the main.swf. Do u have any Idea?

**Comment by Sekhmet** [comment]
Look at https://github.com/Sekhmet/PolskaBotCore/blob/develop/Core/VanillaClient.cs#L108

**Comment by delemojo** [comment]
I get that, I generate the StageOne code on the remote and send it to the client. But than I dont recieve any packet. Could it be that the Generator is outdated or I oversee something?

**Comment by Sekhmet** [comment]
Make sure your packet is 100% correct or try to ask @CuteQuake

**Comment by delemojo** [comment]
@CuteQuake  send me back here, cause its looking like there is a problem with Fade Proxy, I uploaded it in my Repo if u want to check for it.

**Comment by Sekhmet** [comment]
I no longer use Windows so I'm not able to try this (or find something useful without compiling it).
